=== MyRepDremuk/LangRecognitionService/LanguageRecognitionAPI/XmlData/languageXML.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="friquency_pair" >
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element name="pair">
          <xs:complexType>
            <xs:attribute name="character" type="xs:string"></xs:attribute>
            <xs:attribute name="frequency" type="xs:double"></xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MyRepDremuk/LangRecognitionService/LanguageRecognitionAPI/XmlData/russian.xml
<?xml version="1.0" encoding="utf-8" ?>
<friquency_pair xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "languageXML.xsd">
  <pair character="о" frequency="0.0928"></pair>
  <pair character="а" frequency="0.0866"></pair>
  <pair character="е" frequency="0.081"></pair>
  <pair character="ё" frequency="0.081"></pair>
  <pair character="и" frequency="0.0745"></pair>
  <pair character="н" frequency="0.0635"></pair>
  <pair character="т" frequency="0.063"></pair>
  <pair character="р" frequency="0.0553"></pair>
  <pair character="с" frequency="0.0545"></pair>
  <pair character="л" frequency="0.0432"></pair>
  <pair character="в" frequency="0.0419"></pair>
  <pair character="к" frequency="0.0347"></pair>
  <pair character="п" frequency="0.0335"></pair>
  <pair character="м" frequency="0.0329"></pair>
  <pair character="у" frequency="0.029"></pair>
  <pair character="д" frequency="0.0256"></pair>
  <pair character="я" frequency="0.0222"></pair>
  <pair character="ы" frequency="0.0211"></pair>
  <pair character="ь" frequency="0.019"></pair>
  <pair character="з" frequency="0.0181"></pair>
  <pair character="б" frequency="0.0151"></pair>
  <pair character="г" frequency="0.0141"></pair>
  <pair character="й" frequency="0.0131"></pair>
  <pair character="ч" frequency="0.0127"></pair>
  <pair character="ю" frequency="0.0103"></pair>
  <pair character="х" frequency="0.0092"></pair>
  <pair character="ж" frequency="0.0078"></pair>
  <pair character="ш" frequency="0.0077"></pair>
  <pair character="ц" frequency="0.0052"></pair>
  <pair character="щ" frequency="0.0049"></pair>
  <pair character="ф" frequency="0.004"></pair>
  <pair character="э" frequency="0.0017"></pair>
  <pair character="ъ" frequency="0.0004"></pair>
</friquency_pair>

=== MyRepDremuk/LangRecognitionService/LanguageRecognitionAPI/XmlData/english.xml
<?xml version="1.0" encoding="utf-8" ?>
<friquency_pair xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "languageXML.xsd">
<pair character="e" frequency="0.12492"></pair>
<pair character="t" frequency="0.09276"></pair>
<pair character="a" frequency="0.08041"></pair>
<pair character="o" frequency="0.07641"></pair>
<pair character="i" frequency="0.07569"></pair>
<pair character="n" frequency="0.07234"></pair>
<pair character="s" frequency="0.06513"></pair>
<pair character="r" frequency="0.06279"></pair>
<pair character="h" frequency="0.05053"></pair>
<pair character="l" frequency="0.04069"></pair>
<pair character="d" frequency="0.03817"></pair>
<pair character="c" frequency="0.03344"></pair>
<pair character="u" frequency="0.0273"></pair>
<pair character="m" frequency="0.02512"></pair>
<pair character="f" frequency="0.02403"></pair>
<pair character="p" frequency="0.02136"></pair>
<pair character="g" frequency="0.01869"></pair>
<pair character="w" frequency="0.01676"></pair>
<pair character="y" frequency="0.01665"></pair>
<pair character="b" frequency="0.01485"></pair>
<pair character="v" frequency="0.01053"></pair>
<pair character="k" frequency="0.00541"></pair>
<pair character="x" frequency="0.00235"></pair>
<pair character="j" frequency="0.00159"></pair>
<pair character="q" frequency="0.0012"></pair>
<pair character="z" frequency="0.0009"></pair>
</friquency_pair>
